export type Bi = { en: string; zh: string };
export const b = (en: string, zh: string): Bi => ({ en, zh });
export const t = (v: Bi) => `${v.en}（${v.zh}）`;
export const systems = [
  ["hull", "Hull & structure", "船体与结构", "#527e89"],
  ["rig", "Rigging", "索具", "#9a7852"],
  ["sails", "Sails", "帆", "#b6a47e"],
  ["steering", "Steering", "操舵", "#578e8a"],
  ["propulsion", "Propulsion", "动力", "#a57966"],
  ["electrical", "Electrical", "电气", "#bc944e"],
  ["navigation", "Navigation & communications", "导航与通信", "#7587a6"],
  ["safety", "Safety", "安全", "#bf7867"],
  ["anchoring", "Anchoring", "锚泊", "#798b94"],
  ["plumbing", "Plumbing & water", "管路与水", "#6b9ead"],
  ["interior", "Interior", "舱内", "#a79177"],
  ["deck", "Deck hardware", "甲板五金", "#87918c"],
  ["solo", "Singlehanded systems", "单人航行系统", "#8a83a6"],
].map(([id, en, zh, color]) => ({ id, name: b(en, zh), color }));
export const sources = [
  {
    id: "solar-manual",
    name: b("Victron: solar charger installation", "Victron：太阳能控制器安装"),
    url: "https://www.victronenergy.com/media/pg/Manual_SmartSolar_MPPT_75-10_up_to_100-20/en/installation.html",
    locator: b("Sections 4.1, 4.2 and 4.6", "第 4.1、4.2 与 4.6 节"),
    note: b(
      "Reference for mounting, protected battery connection and commissioning order. Charging does not imply independent backup supply. Controller moved away from directly above the battery during audit.",
      "用于安装、受保护电池连接及调试顺序参考；充电不代表独立备用供电。审计中已将控制器移至电池正上方以外。",
    ),
  },
  {
    id: "lines",
    name: b("Lapworth: original lines, 1962", "拉普沃思：1962 年原始型线图"),
    url: "https://cal40.com/files/TEMP006.pdf",
    locator: b(
      "Sheet 204/2, profile and body plan",
      "图纸 204/2，侧视与横剖面",
    ),
    note: b(
      "Inspected scan. Mesh is a hand-reconstructed approximation, not digitized offsets.",
      "已查阅扫描图；网格为人工近似重建，非精确型值数字化。",
    ),
  },
  {
    id: "deck-plan",
    name: b("Lapworth: sections & deck, 1963", "拉普沃思：1963 年剖面与甲板图"),
    url: "https://cal40.com/files/TEMP003.pdf",
    locator: b(
      "Sheet 204/5, deck and section views",
      "图纸 204/5，甲板与剖视图",
    ),
    note: b(
      "Arrangement reference; hardware detail is representative.",
      "用于布置参考；五金细节为示意。",
    ),
  },
  {
    id: "interior-plan",
    name: b("Lapworth: cabin plan, 1963", "拉普沃思：1963 年舱室图"),
    url: "https://cal40.com/files/TEMP004.pdf",
    locator: b(
      "Sheet 204/4, cabin plan and inboard profile",
      "图纸 204/4，舱室与内部侧视图",
    ),
    note: b(
      "Berth, galley, and machinery regions reconstructed; refit details differ.",
      "重建铺位、厨房与机械区域；改装细节有所不同。",
    ),
  },
  {
    id: "sail-plan",
    name: b("Lapworth: sail & rig plan, 1963", "拉普沃思：1963 年帆装图"),
    url: "https://cal40.com/files/TEMP005.pdf",
    locator: b("Sheet 204/6, rig elevation", "图纸 204/6，帆装立面"),
    note: b(
      "Sail silhouette and rig arrangement reference; cloth shape is approximate.",
      "帆轮廓与索具布置参考；帆面形状为近似。",
    ),
  },
  {
    id: "dimensions",
    name: b("SailboatData: Cal 40 dimensions", "SailboatData：Cal 40 尺寸"),
    url: "https://sailboatdata.com/sailboat/cal-40/",
    locator: b(
      "Specifications; rig and sail particulars",
      "规格、索具及帆参数",
    ),
    note: b(
      "Baseline: LOA 11.99 m; LWL 9.24 m; beam 3.35 m; draft 1.70 m. I 14.02, J 4.62, P 12.19, E 5.33 m. These do not certify mesh surfaces.",
      "基准：总长 11.99 米，水线长 9.24 米，船宽 3.35 米，吃水 1.70 米；I 14.02、J 4.62、P 12.19、E 5.33 米。这些数值不代表曲面已精确认证。",
    ),
  },
  {
    id: "rules",
    name: b("Cal 40 association: class rules", "Cal 40 协会：级别规则"),
    url: "https://www.cal40.com/rules.shtml",
    locator: b("Section 3: mast and rigging", "第 3 节：桅杆与索具"),
    note: b(
      "Published rig figures differ from database baseline. Kept as separate limits, not averaged.",
      "公布的帆装数值与数据库基准不同；作为独立限制记录，不取平均值。",
    ),
  },
  {
    id: "pilot",
    name: b("Raymarine: autopilot drives", "Raymarine：自动舵驱动装置"),
    url: "https://www.raymarine.com/en-gb/learning/online-guides/selecting-your-raymarine-drive-unit",
    locator: b("Mechanical linear drives", "机械直线驱动装置"),
    note: b(
      "A drive acts through a tiller arm; controller, sensor, and power form distinct dependencies. Installation here is illustrative, not a product sizing recommendation.",
      "驱动器通过舵臂作用；控制器、传感器和电源是不同依赖。本装置为示意，不是产品选型建议。",
    ),
  },
  {
    id: "network",
    name: b("Raymarine: control network", "Raymarine：控制网络"),
    url: "https://docs.raymarine.com/87424/en-US/latest/SeaTalkngConnection-305A50C7.html",
    locator: b("Basic Evolution system diagram", "基本 Evolution 系统图"),
    note: b(
      "Supports separation of sensor, controller, actuator and power. Exact wiring is representative.",
      "支持传感、控制、执行与供电的区分；具体接线为示意。",
    ),
  },
  {
    id: "sheet",
    name: b("Harken: mainsheet systems", "Harken：主帆缭绳系统"),
    url: "https://gallery.harken.com/gallery/d74c32bb-3b7d-4a7e-b503-0c7ccfc75b9b.pdf",
    locator: b("Two-speed mainsheet instruction sheet", "双速主帆缭绳说明书"),
    note: b(
      "Reference for reeving principles only; the modeled single-speed purchase is illustrative and is not a specified Harken kit.",
      "仅作穿绳原理参考；模型中的单速滑轮组为示意，并非指定 Harken 套件。",
    ),
  },
  {
    id: "sss",
    name: b("Singlehanded Sailing Society", "单人航海协会"),
    url: "https://sfbaysss.org/shtp2025/",
    locator: b(
      "2025 Singlehanded Transpac resources",
      "2025 年单人跨太平洋赛事资源",
    ),
    note: b(
      "Offshore learning context. Scenarios are conceptual walkthroughs, not race compliance or a vessel-specific operating checklist.",
      "远洋学习背景。情景为概念演示，不代表赛事合规或特定船舶操作清单。",
    ),
  },
  {
    id: "representative",
    name: b("Declared engineering assumptions", "明确声明的工程假设"),
    url: "",
    locator: b("Atlas representative refit", "图谱示意改装配置"),
    note: b(
      "Equipment geometry, circuit topology, tank volumes and performance coefficients are illustrative unless separately cited. No exact installation or capacity is asserted.",
      "除单独引用外，设备几何、电路拓扑、水箱容量及性能系数均为示意，不宣称实际安装或容量。",
    ),
  },
];
export type Part = {
  id: string;
  system: string;
  name: Bi;
  description: Bi;
  evidence: "approximated" | "illustrative";
  sources: string[];
  abstract?: boolean;
};
const rows: [string, string, string, string, string, string][] = [
  [
    "hull",
    "hull",
    "Hull shell",
    "船壳",
    "Keeps water out and carries distributed loads. Inspect the curved shell in section.",
    "隔绝海水并承受分布载荷；可通过剖面观察弯曲船壳。",
  ],
  [
    "deck",
    "hull",
    "Deck",
    "甲板",
    "Closes the hull above and supports working areas and fittings.",
    "封闭船体上部，支撑操作区域和配件。",
  ],
  [
    "cabin",
    "hull",
    "Coachroof",
    "舱顶",
    "Creates cabin headroom; openings connect cockpit and interior.",
    "提供舱内净高；开口连接驾驶舱与舱内。",
  ],
  [
    "keel",
    "hull",
    "Fin keel",
    "鳍式龙骨",
    "Provides lateral resistance; the deep ballast contributes righting moment.",
    "提供侧向阻力；深处压载产生复原力矩。",
  ],
  [
    "ballast",
    "hull",
    "Lead ballast",
    "铅压载",
    "Places weight low in the keel; the internal shape is illustrative.",
    "将重量置于龙骨低处；内部形状为示意。",
  ],
  [
    "bulkhead",
    "hull",
    "Main bulkhead",
    "主舱壁",
    "Connects hull and deck near the mast; openings preserve cabin access.",
    "在桅杆附近连接船体和甲板；开口保留舱内通道。",
  ],
  [
    "forward-bulkhead",
    "hull",
    "Forward bulkhead",
    "前舱壁",
    "Separates forepeak storage from accommodation.",
    "分隔船首储物舱与居住舱。",
  ],
  [
    "stringer-port",
    "hull",
    "Port stringer",
    "左舷纵桁",
    "Illustrates longitudinal reinforcement bonded to the shell.",
    "示意与船壳粘接的纵向加强构件。",
  ],
  [
    "stringer-starboard",
    "hull",
    "Starboard stringer",
    "右舷纵桁",
    "Illustrates longitudinal reinforcement; laminate schedule is unknown.",
    "示意纵向加强构件；铺层结构未知。",
  ],
  [
    "mast-beam",
    "hull",
    "Mast support beam",
    "桅杆支撑梁",
    "Spreads mast compression into supporting structure.",
    "将桅杆压缩载荷分散至支撑结构。",
  ],
  [
    "mast",
    "rig",
    "Mast",
    "桅杆",
    "Supports sails and transmits compression into the hull structure.",
    "支撑帆并将压缩载荷传入船体结构。",
  ],
  [
    "boom",
    "rig",
    "Boom",
    "帆桁",
    "Supports the mainsail foot and transmits sheet and vang loads.",
    "支撑主帆底边并传递缭绳及下拉索载荷。",
  ],
  [
    "spreader-port",
    "rig",
    "Port spreader",
    "左撑杆",
    "Deflects the cap shroud to brace the mast laterally.",
    "改变上侧支索方向，为桅杆提供侧向支撑。",
  ],
  [
    "spreader-starboard",
    "rig",
    "Starboard spreader",
    "右撑杆",
    "Maintains shroud geometry and lateral mast support.",
    "保持侧支索几何关系与桅杆侧向支撑。",
  ],
  [
    "forestay",
    "rig",
    "Forestay",
    "前支索",
    "Restrains the mast forward and supports the headsail luff.",
    "向前约束桅杆，并支撑前帆前缘。",
  ],
  [
    "backstay",
    "rig",
    "Backstay",
    "后支索",
    "Restrains the mast aft and affects forestay tension.",
    "向后约束桅杆，并影响前支索张力。",
  ],
  [
    "shroud-port",
    "rig",
    "Port cap shroud",
    "左上侧支索",
    "Connects masthead through spreader tip to a chainplate.",
    "经撑杆端部将桅顶连接至链板。",
  ],
  [
    "shroud-starboard",
    "rig",
    "Starboard cap shroud",
    "右上侧支索",
    "Transfers lateral rig loads into the chainplate.",
    "将索具侧向载荷传递至链板。",
  ],
  [
    "lower-port",
    "rig",
    "Port lower shroud",
    "左下侧支索",
    "Supports the lower mast near the spreader root.",
    "在撑杆根部附近支撑桅杆下段。",
  ],
  [
    "lower-starboard",
    "rig",
    "Starboard lower shroud",
    "右下侧支索",
    "Limits lower-mast lateral deflection.",
    "限制桅杆下段侧向挠曲。",
  ],
  [
    "chainplate-port",
    "rig",
    "Port chainplate",
    "左链板",
    "Carries shroud tension into structural attachments below deck.",
    "将侧支索张力传入甲板下结构连接点。",
  ],
  [
    "chainplate-starboard",
    "rig",
    "Starboard chainplate",
    "右链板",
    "Connects standing rigging to the hull structure.",
    "将固定索具连接至船体结构。",
  ],
  [
    "turnbuckle-port",
    "rig",
    "Port turnbuckle",
    "左花篮螺丝",
    "Adjusts effective shroud length and rig tension.",
    "调整侧支索有效长度与索具张力。",
  ],
  [
    "turnbuckle-starboard",
    "rig",
    "Starboard turnbuckle",
    "右花篮螺丝",
    "Tensions the shroud; locking detail is simplified.",
    "张紧侧支索；锁止细节已简化。",
  ],
  [
    "main-halyard",
    "rig",
    "Main halyard",
    "主帆升降索",
    "Runs from sail head over a masthead sheave to the working tail. Pulling raises the sail.",
    "从帆顶经桅顶滑轮通至操作端；拉动可升帆。",
  ],
  [
    "jib-halyard",
    "rig",
    "Jib halyard",
    "前帆升降索",
    "Raises the headsail through its masthead turning point.",
    "经桅顶转向点升起前帆。",
  ],
  [
    "mainsheet",
    "rig",
    "Mainsheet",
    "主帆缭绳",
    "Pulling the reeved purchase draws the boom toward its lower block and increases leech tension.",
    "收紧滑轮组使帆桁靠近下滑轮，并增加帆后缘张力。",
  ],
  [
    "jibsheet-port",
    "rig",
    "Port jib sheet",
    "左前帆缭绳",
    "Leads from clew through a fairlead to a cockpit winch.",
    "从帆后下角经导索器引至驾驶舱绞盘。",
  ],
  [
    "jibsheet-starboard",
    "rig",
    "Starboard jib sheet",
    "右前帆缭绳",
    "The working sheet changes with tack; the other remains unloaded.",
    "换舷后工作缭绳随之切换；另一根保持卸载。",
  ],
  [
    "reef-line",
    "rig",
    "Reefing line",
    "缩帆索",
    "Draws the reef clew down and aft; tack must also be secured.",
    "将缩帆后下角向下向后拉紧；前下角也必须固定。",
  ],
  [
    "vang",
    "rig",
    "Boom vang",
    "帆桁下拉索",
    "Restrains boom rise when the sheet is eased.",
    "放松主帆缭绳时限制帆桁上抬。",
  ],
  [
    "mainsail",
    "sails",
    "Mainsail",
    "主帆",
    "Converts apparent airflow into aerodynamic force; trim changes angle of attack.",
    "将视风转化为气动力；调帆改变迎角。",
  ],
  [
    "jib",
    "sails",
    "Working jib",
    "工作前帆",
    "A smaller headsail forward of the mast; selectable alternative to the genoa.",
    "位于桅杆前方的较小前帆；可与热那亚帆切换。",
  ],
  [
    "genoa",
    "sails",
    "Genoa",
    "热那亚帆",
    "Overlapping headsail for a different sail-area configuration.",
    "后缘越过桅杆的大前帆，提供另一种帆面积配置。",
  ],
  [
    "spinnaker",
    "sails",
    "Spinnaker",
    "球帆",
    "A fuller downwind sail; this simplified demonstration omits detailed cloth dynamics.",
    "较丰满的顺风帆；示意模型省略详细帆布动力学。",
  ],
  [
    "storm-jib",
    "sails",
    "Storm jib",
    "风暴前帆",
    "Small-area sail configuration; exact attachment and area require vessel-specific evidence.",
    "小面积帆配置；具体连接和面积需要实船资料。",
  ],
  [
    "spinnaker-pole",
    "rig",
    "Spinnaker pole",
    "球帆撑杆",
    "Supports the windward spinnaker corner in this representative symmetric setup.",
    "在此示意对称球帆配置中支撑迎风帆角。",
  ],
  [
    "pole-lift",
    "rig",
    "Pole topping lift",
    "球帆杆吊索",
    "Supports the outboard pole end; trim and load limits are not specified.",
    "支撑球帆杆外端；未指定调整及载荷限制。",
  ],
  [
    "afterguy",
    "rig",
    "Spinnaker afterguy",
    "球帆后拉索",
    "Restrains the windward pole end from the aft lead.",
    "从后方导索点约束迎风球帆杆端部。",
  ],
  ["rudder", "steering", "Spade rudder", "独立舵"],
  ["rudder-stock", "steering", "Rudder stock", "舵轴"],
  ["tiller", "steering", "Tiller", "舵柄"],
  ["bearing", "steering", "Rudder bearing", "舵轴承"],
  ["tiller-arm", "steering", "Autopilot tiller arm", "自动舵舵臂"],
  ["engine", "propulsion", "Auxiliary engine", "辅助发动机"],
  ["shaft", "propulsion", "Propeller shaft", "螺旋桨轴"],
  ["propeller", "propulsion", "Propeller", "螺旋桨"],
  ["fuel-tank", "propulsion", "Fuel tank", "燃油箱"],
  ["fuel-line", "propulsion", "Fuel supply line", "供油管"],
  ["exhaust", "propulsion", "Exhaust hose", "排气软管"],
  ["battery", "electrical", "House battery", "生活蓄电池"],
  ["fuse", "electrical", "Main fuse & isolator", "主保险与隔离开关"],
  ["panel", "electrical", "DC distribution panel", "直流配电板"],
  ["solar", "electrical", "Solar panels", "太阳能板"],
  ["controller", "electrical", "Solar charge controller", "太阳能充电控制器"],
  ["alternator", "electrical", "Alternator", "交流发电机"],
  ["shore", "electrical", "Shore-power inlet", "岸电接口"],
  ["charger", "electrical", "Battery charger", "蓄电池充电器"],
  ["bus-wire", "electrical", "DC supply & return", "直流供电与回路"],
  ["ais", "navigation", "AIS transceiver", "AIS 收发机"],
  ["vhf", "navigation", "Fixed VHF radio", "固定甚高频电台"],
  ["gps", "navigation", "Chartplotter / GPS", "海图仪／卫星定位"],
  ["imu", "navigation", "Compass / IMU", "电子罗经／惯性单元"],
  ["depth", "navigation", "Depth transducer", "测深传感器"],
  ["wind", "navigation", "Wind instrument", "风向风速仪"],
  ["antenna", "navigation", "VHF antenna", "甚高频天线"],
  ["handheld", "navigation", "Handheld VHF", "手持甚高频电台"],
  ["backup-gps", "navigation", "Independent GPS", "独立定位仪"],
  ["compass", "navigation", "Magnetic compass", "磁罗经"],
  ["satellite", "navigation", "Satellite communicator", "卫星通信器"],
  ["epirb", "safety", "EPIRB", "应急无线电示位标"],
  ["liferaft", "safety", "Liferaft", "救生筏"],
  ["jackline-port", "safety", "Port jackline", "左舷安全索"],
  ["jackline-starboard", "safety", "Starboard jackline", "右舷安全索"],
  ["tether", "safety", "Safety tether", "安全系绳"],
  ["pfd", "safety", "PFD & harness", "救生衣与安全带"],
  ["extinguisher", "safety", "Fire extinguisher", "灭火器"],
  ["drogue", "safety", "Drogue bag", "拖曳式海锚包"],
  ["anchor", "anchoring", "Anchor", "船锚"],
  ["chain", "anchoring", "Anchor chain", "锚链"],
  ["rode", "anchoring", "Anchor rode", "锚缆"],
  ["windlass", "anchoring", "Windlass", "起锚机"],
  ["water-tank", "plumbing", "Fresh-water tank", "淡水箱"],
  ["water-pump", "plumbing", "Fresh-water pump", "淡水泵"],
  ["water-hose", "plumbing", "Fresh-water hose", "淡水管"],
  ["head", "plumbing", "Marine head", "船用厕所"],
  ["seacock", "plumbing", "Seacock", "海底阀"],
  ["through-hull", "plumbing", "Through-hull fitting", "穿舷接头"],
  ["bilge-pump", "plumbing", "Electric bilge pump", "电动舱底泵"],
  ["manual-pump", "plumbing", "Manual bilge pump", "手动舱底泵"],
  ["bilge-hose", "plumbing", "Bilge discharge hose", "舱底排水管"],
  ["holding-tank", "plumbing", "Holding tank", "污水箱"],
  ["galley", "interior", "Galley", "厨房"],
  ["sink", "interior", "Sink", "水槽"],
  ["berth-port", "interior", "Port berth", "左舷铺位"],
  ["berth-starboard", "interior", "Starboard berth", "右舷铺位"],
  ["v-berth", "interior", "V-berth", "船首 V 形铺位"],
  ["nav-station", "interior", "Navigation station", "导航台"],
  ["food", "interior", "Food storage", "食物储藏"],
  ["sole", "interior", "Cabin sole", "舱内地板"],
  ["steps", "interior", "Companionway steps", "舱口梯"],
  ["traveler", "deck", "Mainsheet traveler", "主帆滑轨"],
  ["traveler-car", "deck", "Traveler car", "滑轨小车"],
  ["block-upper", "deck", "Upper sheet block", "上缭绳滑轮"],
  ["block-lower", "deck", "Lower sheet block", "下缭绳滑轮"],
  ["winch-port", "deck", "Port primary winch", "左主绞盘"],
  ["winch-starboard", "deck", "Starboard primary winch", "右主绞盘"],
  ["halyard-winch", "deck", "Halyard winch", "升降索绞盘"],
  ["cleat-bow", "deck", "Bow cleat", "船首系缆桩"],
  ["cleat-stern", "deck", "Stern cleat", "船尾系缆桩"],
  ["fairlead-port", "deck", "Port sheet fairlead", "左缭绳导索器"],
  ["fairlead-starboard", "deck", "Starboard sheet fairlead", "右缭绳导索器"],
  ["reef-hook", "deck", "Reef tack hook", "缩帆前角钩"],
  ["hatch", "deck", "Forehatch", "前舱盖"],
  ["lifelines", "deck", "Lifelines & stanchions", "护栏索与立柱"],
  ["autopilot", "solo", "Autopilot controller", "自动舵控制器"],
  ["drive", "solo", "Autopilot linear drive", "自动舵直线驱动器"],
  ["windvane", "solo", "Windvane self-steering", "风向自操舵"],
  ["emergency-tiller", "solo", "Emergency tiller", "应急舵柄"],
  ["preventer", "solo", "Boom preventer", "帆桁防意外换舷索"],
  ["heading", "steering", "Boat heading", "船首向"],
  ["aero-force", "sails", "Aerodynamic force", "气动力"],
  ["navigation", "navigation", "Navigation capability", "导航能力"],
  ["communication", "navigation", "Voice communication", "语音通信能力"],
].map((r) => r as [string, string, string, string, string, string]);
const explanations: Record<string, [string, string]> = {
  rudder: [
    "Deflected water flow creates a turning moment; control weakens at low speed.",
    "偏转水流产生转向力矩；低速时控制力减弱。",
  ],
  "rudder-stock": [
    "Transmits tiller torque to the rudder blade.",
    "将舵柄扭矩传至舵叶。",
  ],
  tiller: [
    "Direct mechanical control of the rudder stock.",
    "直接机械控制舵轴。",
  ],
  bearing: [
    "Supports the stock while allowing rotation.",
    "支撑舵轴并允许旋转。",
  ],
  "tiller-arm": [
    "Transfers autopilot drive thrust into stock torque.",
    "将自动舵推力转为舵轴扭矩。",
  ],
  engine: [
    "Supplies shaft power; modeled machinery is a representative diesel installation.",
    "提供轴功率；模型为示意柴油机安装。",
  ],
  shaft: [
    "Carries torque from engine to propeller through the hull.",
    "穿过船壳，将发动机扭矩传给螺旋桨。",
  ],
  propeller: [
    "Accelerates water to produce thrust; blades and pitch are representative.",
    "加速水流产生推力；桨叶和螺距为示意。",
  ],
  "fuel-tank": [
    "Stores fuel separately from potable water; capacity is not asserted.",
    "与饮用水分开储存燃油；不宣称实际容量。",
  ],
  "fuel-line": [
    "Supplies fuel from tank to engine; detailed filtration is omitted.",
    "从油箱向发动机供油；详细过滤装置未展开。",
  ],
  exhaust: [
    "Routes engine exhaust aft; internal cooling and anti-siphon detail is not modeled.",
    "将发动机废气引向船尾；未展开冷却与防虹吸细节。",
  ],
  battery: [
    "Stores electrical energy for the house circuits. Inject a failure to explore dependencies.",
    "为生活电路储存电能；注入故障可探索依赖关系。",
  ],
  fuse: [
    "Protects and isolates the house supply before distribution.",
    "在配电前保护并隔离生活电源。",
  ],
  panel: [
    "Distributes DC supply to individually protected branches.",
    "向独立受保护支路分配直流电。",
  ],
  solar: [
    "Generates power from sunlight; available output depends on conditions.",
    "将阳光转为电能；可用功率取决于环境。",
  ],
  controller: [
    "Regulates solar charging; panel presence alone does not guarantee backup power.",
    "调节太阳能充电；有太阳能板不等于存在可靠备用电源。",
  ],
  alternator: [
    "Converts engine mechanical power into charging current.",
    "将发动机机械功率转为充电电流。",
  ],
  shore: [
    "Connects external shore supply when docked; not an offshore power source.",
    "靠泊时接入岸电；不是远洋电源。",
  ],
  charger: [
    "Converts shore supply to controlled battery charging.",
    "将岸电转换为受控蓄电池充电。",
  ],
  "bus-wire": [
    "Shows a paired supply and return route; conductor sizes are unspecified.",
    "显示成对供电与回路路径；未指定导线规格。",
  ],
  ais: [
    "Shares vessel data by VHF; losing its circuit stops this modeled transceiver.",
    "经甚高频共享船舶数据；其电路失效会停用模型中的收发机。",
  ],
  vhf: [
    "Fixed voice radio depends on house power and an antenna.",
    "固定语音电台依赖生活电源与天线。",
  ],
  gps: [
    "Displays position and charts; this unit uses the house circuit.",
    "显示位置与海图；此设备由生活电路供电。",
  ],
  imu: [
    "Senses heading and motion for the autopilot feedback loop.",
    "测量首向及运动，为自动舵提供反馈。",
  ],
  depth: [
    "Measures water depth beneath its installed reference point.",
    "测量安装参考点下方水深。",
  ],
  wind: [
    "Measures local wind; masthead position and calibration affect readings.",
    "测量局部风；桅顶安装位置和校准影响读数。",
  ],
  antenna: [
    "Provides the radio transmission path; antenna failure differs from power loss.",
    "提供无线电传输路径；天线故障与失电不同。",
  ],
  handheld: [
    "Independent battery-powered radio, when enabled in the backup configuration.",
    "备用配置启用时，使用独立电池的电台。",
  ],
  "backup-gps": [
    "Independent position source; backup availability is a configurable assumption.",
    "独立定位来源；备用可用性是可配置假设。",
  ],
  compass: [
    "Passive heading reference independent of house electrical power.",
    "不依赖生活电源的被动首向参考。",
  ],
  satellite: [
    "Representative independent communicator; subscription and coverage are not simulated.",
    "示意独立通信器；不模拟订阅和覆盖范围。",
  ],
  epirb: [
    "Dedicated distress beacon with its own battery; placement is representative.",
    "配备独立电池的遇险示位标；位置为示意。",
  ],
  liferaft: [
    "Stowed survival equipment; launch and securing arrangements need boat-specific review.",
    "存放的救生设备；释放和固定方式需实船核查。",
  ],
  "jackline-port": [
    "Provides a tether attachment route along the working deck.",
    "沿作业甲板提供安全系绳连接路线。",
  ],
  "jackline-starboard": [
    "Provides a second attachment route; geometry alone does not prove fall prevention.",
    "提供另一条连接路线；几何模型不证明防坠效果。",
  ],
  tether: [
    "Connects harness to an attachment point; inspect reach and exposure.",
    "连接安全带与固定点；检查可达范围与暴露风险。",
  ],
  pfd: [
    "Provides buoyancy and a harness attachment interface.",
    "提供浮力及安全系绳连接接口。",
  ],
  extinguisher: [
    "Accessible fire-response equipment; selection is installation-specific.",
    "可接近的灭火设备；选型取决于实际安装。",
  ],
  drogue: [
    "Stowed drag device; deployment loads and attachment design are not certified.",
    "收纳的拖曳减速装置；布放载荷与连接设计未经认证。",
  ],
  anchor: [
    "Transfers holding load into the seabed through the rode.",
    "通过锚缆将保持载荷传入海床。",
  ],
  chain: [
    "Connects anchor to rode; working load and length are unspecified.",
    "连接锚与锚缆；未指定工作载荷及长度。",
  ],
  rode: [
    "Transmits anchoring load; stowed here below the foredeck.",
    "传递锚泊载荷；此处收纳于前甲板下。",
  ],
  windlass: [
    "Recovers rode using power; this is a representative optional refit.",
    "使用动力回收锚缆；为示意可选改装。",
  ],
  "water-tank": [
    "Stores fresh water; inspect the shell using the tank cutaway control.",
    "储存淡水；可通过水箱剖视控制观察壳体。",
  ],
  "water-pump": [
    "Pressurizes fresh water for the galley; depends on house power.",
    "为厨房淡水加压；依赖生活电源。",
  ],
  "water-hose": [
    "Connects tank, pump and sink without crossing fuel systems.",
    "连接水箱、水泵与水槽，不与燃油系统混接。",
  ],
  head: [
    "Represents a marine toilet with a holding-tank connection.",
    "示意连接污水箱的船用厕所。",
  ],
  seacock: [
    "Allows a through-hull flow path to be shut off.",
    "允许关闭穿舷水流通路。",
  ],
  "through-hull": [
    "Penetrates the hull; connected seacock controls the opening.",
    "穿过船壳；连接的海底阀控制开口。",
  ],
  "bilge-pump": [
    "Removes bilge water electrically; loss of supply requires another method.",
    "电动排出舱底积水；失电后需要其他方法。",
  ],
  "manual-pump": [
    "Human-powered bilge pumping alternative independent of DC supply.",
    "不依赖直流电的人工舱底排水替代方案。",
  ],
  "bilge-hose": [
    "Carries discharge to an above-waterline outlet; routing is illustrative.",
    "将排水送至水线上排口；路径为示意。",
  ],
  "holding-tank": [
    "Retains waste; pump-out and vent detail are not modeled.",
    "储存污水；未展开抽排口及通气细节。",
  ],
  galley: [
    "Food preparation region near the companionway.",
    "靠近舱口的食物准备区域。",
  ],
  sink: [
    "Receives fresh water; drain details are simplified.",
    "接收淡水；排水细节已简化。",
  ],
  "berth-port": [
    "Port sleeping space informed by the original cabin plan.",
    "参考原始舱室图的左舷睡眠空间。",
  ],
  "berth-starboard": [
    "Starboard sleeping space informed by the original plan.",
    "参考原始图纸的右舷睡眠空间。",
  ],
  "v-berth": [
    "Forward sleeping space above storage.",
    "储物空间上方的前舱睡眠区。",
  ],
  "nav-station": [
    "Work surface for passage planning and electronics.",
    "用于航行规划和电子设备的工作台。",
  ],
  food: [
    "Representative secured storage for offshore provisions.",
    "示意固定的远洋补给储物空间。",
  ],
  sole: [
    "Walking surface above bilge and structural spaces.",
    "位于舱底和结构空间上方的行走面。",
  ],
  steps: [
    "Connects cockpit access to cabin sole.",
    "连接驾驶舱入口与舱内地板。",
  ],
  traveler: [
    "Moves the sheet attachment across the boat to change boom angle.",
    "横向移动缭绳连接点，以改变帆桁角度。",
  ],
  "traveler-car": [
    "Carries the lower sheet block on the transverse track.",
    "在横向滑轨上承载下缭绳滑轮。",
  ],
  "block-upper": [
    "Reverses sheet direction at the boom; repeated passes share load.",
    "在帆桁处改变缭绳方向；多段绳共同承载。",
  ],
  "block-lower": [
    "Reverses sheet direction at the traveler; the tail leads to the sailor.",
    "在滑轨处改变缭绳方向；绳尾引向操作者。",
  ],
  "winch-port": [
    "Mechanical advantage for the port sheet.",
    "为左缭绳提供机械增益。",
  ],
  "winch-starboard": [
    "Mechanical advantage for the starboard sheet.",
    "为右缭绳提供机械增益。",
  ],
  "halyard-winch": [
    "Assists halyard tensioning at the mast.",
    "在桅杆处辅助张紧升降索。",
  ],
  "cleat-bow": ["Secures mooring lines at the bow.", "在船首固定系泊缆。"],
  "cleat-stern": ["Secures mooring lines at the stern.", "在船尾固定系泊缆。"],
  "fairlead-port": [
    "Sets the port headsail sheet lead toward the winch.",
    "确定通向绞盘的左前帆缭绳导向。",
  ],
  "fairlead-starboard": [
    "Sets the starboard headsail sheet lead.",
    "确定右前帆缭绳导向。",
  ],
  "reef-hook": [
    "Secures the reef tack near the gooseneck.",
    "在帆桁鹅颈接头附近固定缩帆前角。",
  ],
  hatch: [
    "Provides forecabin access and ventilation when conditions allow.",
    "条件允许时提供前舱出入和通风。",
  ],
  lifelines: [
    "Defines a deck-edge barrier; never a substitute for secure attachment.",
    "构成甲板边缘护栏；不能替代可靠的安全连接。",
  ],
  autopilot: [
    "Compares target and measured heading, commanding the drive. Follow its power and feedback paths.",
    "比较目标与实测首向，并指令驱动器；可追踪供电和反馈路径。",
  ],
  drive: [
    "Pushes a dedicated tiller arm; disengagement permits manual steering.",
    "推动独立舵臂；脱开后允许手动操舵。",
  ],
  windvane: [
    "Representative mechanical self-steering alternative; details and operating envelope are illustrative.",
    "示意机械自操舵替代方案；细节与适用范围为示意。",
  ],
  "emergency-tiller": [
    "Stored alternative for a usable rudder stock; it cannot repair a missing rudder.",
    "可用舵轴的收纳式替代操纵装置；无法修复丢失的舵。",
  ],
  preventer: [
    "Restrains unwanted boom movement; attachment and release remain load-dependent.",
    "限制非预期帆桁移动；连接与释放取决于载荷。",
  ],
  heading: [
    "Direction of the bow, distinct from course over ground.",
    "船首指向，与对地航向不同。",
  ],
  "aero-force": [
    "Resultant of lift and drag; coefficients are educational assumptions.",
    "升力与阻力的合力；系数为教学假设。",
  ],
  navigation: [
    "Position-finding capability can survive loss of a fixed plotter with an independent backup.",
    "具备独立备用设备时，固定海图仪失效后仍可保留定位能力。",
  ],
  communication: [
    "Voice capability may continue on an independent handheld after fixed-radio power loss.",
    "固定电台失电后，可通过独立手持电台保留语音能力。",
  ],
};
const approximate = new Set([
  "hull",
  "deck",
  "cabin",
  "keel",
  "rudder",
  "mast",
  "boom",
  "mainsail",
  "jib",
  "berth-port",
  "berth-starboard",
  "v-berth",
  "galley",
  "nav-station",
]);
export const parts: Part[] = rows.map(([id, system, en, zh, de, dz]) => ({
  id,
  system,
  name: b(en, zh),
  description: b(de || explanations[id][0], dz || explanations[id][1]),
  evidence: approximate.has(id) ? "approximated" : "illustrative",
  sources:
    system === "hull" || id === "rudder"
      ? ["lines", "deck-plan", "dimensions"]
      : system === "interior"
        ? ["interior-plan"]
        : system === "rig" || system === "sails"
          ? ["sail-plan", ...(id === "mainsheet" ? ["sheet"] : [])]
          : ["autopilot", "drive", "tiller-arm", "imu"].includes(id)
            ? ["pilot", "network", "representative"]
            : ["representative"],
  abstract: ["heading", "aero-force", "navigation", "communication"].includes(
    id,
  ),
}));
export const byId = Object.fromEntries(parts.map((p) => [p.id, p]));
export const relationLabels: Record<string, Bi> = {
  power: b("powers", "供电"),
  charge: b("charges", "充电"),
  mechanical: b("transmits motion / load", "传递运动／载荷"),
  sense: b("is measured by", "由其测量"),
  feedback: b("reports measurements to", "向其反馈测量"),
  command: b("commands", "指令"),
  effect: b("changes", "改变"),
  route: b("routes through", "路径经过"),
  alternative: b("backs up", "提供备用"),
  flow: b("supplies fluid", "供应流体"),
  support: b("supports", "支撑"),
  mounted: b("mounted in / on", "安装于"),
  stores: b("stores", "收纳"),
  informs: b("informs decisions", "辅助判断"),
};
export type Edge = {
  from: string;
  to: string;
  type: string;
  source: string;
  note: Bi;
};
const links: [string, string, string, string?][] = [
  ["deck", "hull", "mechanical"],
  ["cabin", "deck", "mounted"],
  ["forward-bulkhead", "hull", "mechanical"],
  ["stringer-port", "hull", "mechanical"],
  ["stringer-starboard", "hull", "mechanical"],
  ["lower-port", "chainplate-port", "mechanical"],
  ["lower-starboard", "chainplate-starboard", "mechanical"],
  ["shroud-port", "turnbuckle-port", "mechanical"],
  ["shroud-starboard", "turnbuckle-starboard", "mechanical"],
  ["turnbuckle-port", "chainplate-port", "mechanical"],
  ["turnbuckle-starboard", "chainplate-starboard", "mechanical"],
  ["forestay", "genoa", "support"],
  ["forestay", "storm-jib", "support"],
  ["bearing", "rudder-stock", "support"],
  ["engine", "exhaust", "flow"],
  ["bus-wire", "panel", "power"],
  ["depth", "navigation", "informs"],
  ["wind", "autopilot", "informs"],
  ["satellite", "nav-station", "mounted"],
  ["epirb", "cabin", "mounted"],
  ["liferaft", "deck", "mounted"],
  ["extinguisher", "cabin", "mounted"],
  ["drogue", "deck", "mounted"],
  ["galley", "sink", "support"],
  ["berth-port", "hull", "mounted"],
  ["berth-starboard", "hull", "mounted"],
  ["v-berth", "hull", "mounted"],
  ["nav-station", "gps", "support"],
  ["food", "hull", "mounted"],
  ["sole", "hull", "mounted"],
  ["steps", "sole", "support"],
  ["cleat-bow", "deck", "mounted"],
  ["cleat-stern", "deck", "mounted"],
  ["hatch", "cabin", "mounted"],
  ["lifelines", "deck", "mounted"],

  ["battery", "fuse", "power"],
  ["fuse", "bus-wire", "power"],
  ["panel", "autopilot", "power"],
  ["panel", "drive", "power"],
  ["panel", "imu", "power"],
  ["panel", "ais", "power"],
  ["panel", "vhf", "power"],
  ["panel", "gps", "power"],
  ["panel", "depth", "power"],
  ["panel", "wind", "power"],
  ["panel", "bilge-pump", "power"],
  ["panel", "water-pump", "power"],
  ["panel", "windlass", "power"],
  ["solar", "controller", "charge"],
  ["controller", "battery", "charge"],
  ["engine", "alternator", "mechanical"],
  ["alternator", "battery", "charge"],
  ["shore", "charger", "power"],
  ["charger", "battery", "charge"],
  ["imu", "autopilot", "feedback", "network"],
  ["autopilot", "drive", "command", "pilot"],
  ["drive", "tiller-arm", "mechanical", "pilot"],
  ["tiller-arm", "rudder-stock", "mechanical", "pilot"],
  ["tiller", "rudder-stock", "mechanical"],
  ["rudder-stock", "rudder", "mechanical"],
  ["rudder", "heading", "effect"],
  ["heading", "imu", "sense", "network"],
  ["handheld", "communication", "alternative"],
  ["vhf", "communication", "effect"],
  ["gps", "navigation", "effect"],
  ["backup-gps", "navigation", "alternative"],
  ["heading", "compass", "sense"],
  ["windvane", "tiller", "mechanical"],
  ["emergency-tiller", "rudder-stock", "alternative"],
  ["manual-pump", "bilge-pump", "alternative"],
  ["mast", "spinnaker-pole", "support"],
  ["pole-lift", "spinnaker-pole", "support"],
  ["afterguy", "spinnaker-pole", "mechanical"],
  ["spinnaker-pole", "spinnaker", "support"],
  ["mainsheet", "block-lower", "route", "sheet"],
  ["mainsheet", "block-upper", "route", "sheet"],
  ["traveler", "traveler-car", "support"],
  ["traveler-car", "block-lower", "support"],
  ["block-upper", "boom", "mechanical", "sheet"],
  ["boom", "mainsail", "effect", "sail-plan"],
  ["mainsail", "aero-force", "effect"],
  ["aero-force", "heading", "effect"],
  ["mast", "boom", "support", "sail-plan"],
  ["mast", "spreader-port", "support"],
  ["mast", "spreader-starboard", "support"],
  ["shroud-port", "chainplate-port", "mechanical"],
  ["shroud-starboard", "chainplate-starboard", "mechanical"],
  ["chainplate-port", "hull", "mechanical"],
  ["chainplate-starboard", "hull", "mechanical"],
  ["forestay", "mast", "support"],
  ["backstay", "mast", "support"],
  ["main-halyard", "mainsail", "mechanical"],
  ["main-halyard", "halyard-winch", "route"],
  ["jib-halyard", "jib", "mechanical"],
  ["jibsheet-port", "fairlead-port", "route"],
  ["jibsheet-port", "winch-port", "route"],
  ["jibsheet-starboard", "fairlead-starboard", "route"],
  ["jibsheet-starboard", "winch-starboard", "route"],
  ["reef-line", "mainsail", "effect"],
  ["reef-hook", "mainsail", "support"],
  ["vang", "boom", "mechanical"],
  ["preventer", "boom", "mechanical"],
  ["fuel-tank", "fuel-line", "flow"],
  ["fuel-line", "engine", "flow"],
  ["engine", "shaft", "mechanical"],
  ["shaft", "propeller", "mechanical"],
  ["water-tank", "water-pump", "flow"],
  ["water-pump", "water-hose", "flow"],
  ["water-hose", "sink", "flow"],
  ["head", "holding-tank", "flow"],
  ["through-hull", "seacock", "flow"],
  ["seacock", "head", "flow"],
  ["bilge-pump", "bilge-hose", "flow"],
  ["anchor", "chain", "mechanical"],
  ["chain", "rode", "mechanical"],
  ["windlass", "chain", "mechanical"],
  ["pfd", "tether", "mechanical"],
  ["tether", "jackline-port", "mechanical"],
  ["tether", "jackline-starboard", "mechanical"],
  ["mast", "mast-beam", "mechanical"],
  ["mast-beam", "bulkhead", "mechanical"],
  ["keel", "ballast", "support"],
  ["hull", "keel", "support"],
  ["antenna", "vhf", "support"],
];
export const edges: Edge[] = links.map(([from, to, type, source]) => ({
  from,
  to,
  type,
  source: source || "representative",
  note: b(
    `${byId[from].name.en} → ${byId[to].name.en}: ${relationLabels[type].en}. This relationship applies to the illustrated configuration.`,
    `${byId[from].name.zh} → ${byId[to].name.zh}：${relationLabels[type].zh}。此关系适用于本示意配置。`,
  ),
}));
export const scenarios = [
  [
    "reef",
    "Reef the mainsail",
    "主帆缩帆",
    ["pfd", "autopilot", "main-halyard", "reef-hook", "reef-line", "mainsheet"],
  ],
  [
    "headsail",
    "Change headsail",
    "更换前帆",
    ["tether", "jackline-port", "jibsheet-port", "jib-halyard", "storm-jib"],
  ],
  [
    "pilot",
    "Autopilot failure",
    "自动舵故障",
    ["autopilot", "tiller", "fuse", "drive", "windvane"],
  ],
  [
    "weather",
    "Heavy-weather preparation",
    "恶劣天气准备",
    ["pfd", "reef-line", "storm-jib", "hatch", "drogue"],
  ],
  [
    "night",
    "Night sailing",
    "夜航",
    ["tether", "ais", "vhf", "gps", "battery"],
  ],
  [
    "squall",
    "Squall approaching",
    "飑风接近",
    ["wind", "reef-line", "mainsheet", "jibsheet-port", "tiller"],
  ],
  [
    "power",
    "Loss of electrical power",
    "电力丧失",
    ["battery", "tiller", "fuse", "handheld", "backup-gps", "manual-pump"],
  ],
  [
    "steering",
    "Steering failure",
    "操舵故障",
    ["tiller", "rudder-stock", "drive", "emergency-tiller", "drogue"],
  ],
  [
    "mob",
    "Man-overboard prevention",
    "防止人员落水",
    ["pfd", "tether", "jackline-port", "jackline-starboard"],
  ],
  [
    "trades",
    "Entering the trade winds",
    "进入信风带",
    ["wind", "mainsheet", "preventer", "solar", "windvane"],
  ],
  [
    "arrival",
    "Preparing for Hawaii",
    "抵达夏威夷准备",
    ["gps", "vhf", "engine", "anchor", "chain", "cleat-bow"],
  ],
].map(([id, en, zh, steps]) => ({
  id: id as string,
  name: b(en as string, zh as string),
  steps: steps as string[],
}));
export const stepNotes: Record<string, Bi> = {
  pfd: b(
    "Review personal flotation and harness attachment before moving on deck.",
    "上甲板前检查个人浮力与安全带连接。",
  ),
  autopilot: b(
    "Check heading control and dependencies; retain immediate access to manual steering.",
    "检查首向控制及依赖；保持可立即手动操舵。",
  ),
  "main-halyard": b(
    "Observe how lowering the halyard changes the sail head; use the reef control to compare geometry.",
    "观察松降升降索如何改变帆顶位置；用缩帆控制比较几何。",
  ),
  "reef-hook": b(
    "Identify the reef tack securing point before retensioning the halyard.",
    "重新张紧升降索前识别缩帆前角固定点。",
  ),
  "reef-line": b(
    "Trace the reef clew line: its pull must act down and aft. Exact procedures depend on the installed system.",
    "追踪缩帆后角索：拉力应向下向后；具体步骤取决于所安装系统。",
  ),
  mainsheet: b(
    "Explore easing and trimming: watch boom angle, sail area and force change.",
    "探索放松和收紧：观察帆桁角度、帆面积与力的变化。",
  ),
  tiller: b(
    "Identify direct steering and the connection to the rudder stock.",
    "识别直接操舵方式及其与舵轴的连接。",
  ),
  battery: b(
    "Inject house-bank loss and inspect the affected functions and independent alternatives.",
    "注入生活电池故障，检查受影响功能及独立替代方案。",
  ),
  fuse: b(
    "Distinguish a main-supply failure from a local branch failure; inspect the graph.",
    "区分主电源故障与局部支路故障；检查图谱。",
  ),
  drive: b(
    "Inspect the actuator-to-tiller-arm connection; a jammed drive is different from simple loss of power.",
    "检查执行器至舵臂连接；驱动器卡死与单纯失电不同。",
  ),
  "emergency-tiller": b(
    "Check whether the rudder stock and blade remain usable; an emergency tiller does not replace a lost blade.",
    "检查舵轴和舵叶是否仍可用；应急舵柄不能替代丢失的舵叶。",
  ),
};
